services:
  app:
    build:
      context: .
      dockerfile: ./docker/${ENVIRONMENT}/app/Dockerfile
      args:
        PORT: ${PORT}
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    extends:
      file: ./docker/app.yml
      service: ${ENVIRONMENT}
    networks:
      - stack
    ports:
      - ${PORT}:3000
    restart: unless-stopped
    volumes:
      - data_app:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    healthcheck:
      test: curl --fail -s ${NEXT_PUBLIC_API_URL}/api/status || exit 1
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 4

  nginx:
    build: 
      context: ./docker/nginx
    environment:
      PORT: ${PORT}
    links:
      - app
    ports:
      - 80:80
    restart: always
    networks:
      - stack
  
volumes:
  data_app:
    name: ${DATA_APP}
    external: true
  node_modules:
  build:

networks:
  stack:
    external: true
    name: ${APP_NAME}_network